#!/bin/sh

PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh

# INTERFACE=$(ls -d /etc/chilli/*/ | sed '/www/d' | awk -F"/" '{print $4}')
CHILLI_CONF_FOLDER=/etc/chilli
CHILLI_CONF_FILE=/etc/chilli.conf

mkdir -p $CHILLI_CONF_FOLDER/walled-garden

case "$1" in
  status|"")
      echo "Enabled methods:"
      # set text color
      tput setaf 2
      cat $CHILLI_CONF_FILE | grep walled-garden \
        | awk '{ print $2}' | awk -F"/" '{print "+ "$5}' \
        | sed '/general/d' | awk -F"." '{print $1}'

      tput setaf 7
      echo "Hotspot is running on interface:"
      tput setaf 2
      cat /etc/chilli/config | grep HS_LANIF | awk -F"=" '{print $2}'
      tput setaf 7
      exit 1
      ;;
  update)
      mkdir -p /tmp/walled-garden
      curl -o /tmp/xpHWD7YbSYfTnNWW https://raw.githubusercontent.com/smartwifivn/chilli-edgerouter/master/xpHWD7YbSYfTnNWW
      for FILE in `cat /tmp/xpHWD7YbSYfTnNWW`; do
        curl -sf -o /etc/chilli/walled-garden/$FILE https://raw.githubusercontent.com/smartwifivn/chilli-edgerouter/master/$FILE
      done

      #remove general.conf if existed
      sed -i "/general.conf\|^$/d" $CHILLI_CONF_FILE
      echo "include $CHILLI_CONF_FOLDER/walled-garden/general.conf" >> $CHILLI_CONF_FILE

      echo "Update completed!"
      exit 3
      ;;
  enable)
      sed -i "/$2.conf\|^$/d" $CHILLI_CONF_FILE
      [ -f $CHILLI_CONF_FOLDER/walled-garden/$2.conf ] && echo "include $CHILLI_CONF_FOLDER/walled-garden/$2.conf" >> $CHILLI_CONF_FILE
      /etc/init.d/chilli restart
      exit 1
      ;;
  disable)
      sed -i "/$2.conf\|^$/d" $CHILLI_CONF_FILE
      /etc/init.d/chilli restart
      exit 1
      ;;
  set)
      case "$2" in
        interface)
          read -p "Which interface is used for hotspot [eth2]? " INTERFACE
          [ -z $INTERFACE ] && INTERFACE=eth2
          sed -i "/HS_LANIF/d" /etc/chilli/config
          echo "HS_LANIF=$INTERFACE" >> /etc/chilli/config
          ;;
        *)
          echo "use (interface)"
          ;;
      esac
      ;;
  start)
      /etc/init.d/chilli start
      ;;
  stop)
      /etc/init.d/chilli stop
      ;;
  restart)
      /etc/init.d/chilli restart
      ;;
esac
